# AutoQuant scoring method ("gradient" or "kl_div").
method: gradient

# Torch device used for calibration/scoring (e.g., "cuda", "cuda:0", "cpu").
device: cuda

# Calibration batch size (samples per forward/score step).
batch_size: 8

# AutoQuant constraint: effective bits budget for the chosen quantization format.
effective_bits: 8.0

# AutoQuant score size expressed in samples (the runner converts this to steps).
score_size: 128

# Whether to enable verbose ModelOpt logging during AutoQuant.
verbose: true
