#!/usr/bin/env bash
set -euo pipefail

# Materialize a small set of YOLOv10m low-bit (FP8) candidates from a scheme directory.
#
# Expects scheme files generated by:
#   scripts/cv-models/make_yolov10m_candidate_schemes.py
#
# Usage:
#   RUN_ROOT="tmp/yolov10m_lowbit/<run-id>" \
#   CALIB_PATH="tmp/yolov10m_lowbit/<run-id>/calib/calib_yolov10m_640.npy" \
#   pixi run -e rtx5090 bash scripts/cv-models/materialize_yolov10m_lowbit_candidates.sh
#
# Customize:
#   KS="0 5 10 20"
#   ONNX_PATH="models/cv-models/yolov10m/checkpoints/yolov10m.onnx"
#   SCHEMES_DIR="$RUN_ROOT/schemes"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

RUN_ROOT="${RUN_ROOT:-${REPO_ROOT}/tmp/yolov10m_lowbit/$(date +%Y-%m-%d_%H-%M-%S)}"
ONNX_PATH="${ONNX_PATH:-${REPO_ROOT}/models/cv-models/yolov10m/checkpoints/yolov10m.onnx}"
CALIB_PATH="${CALIB_PATH:-${RUN_ROOT}/calib/calib_yolov10m_640.npy}"
SCHEMES_DIR="${SCHEMES_DIR:-${RUN_ROOT}/schemes}"
KS="${KS:-0 5 10 20}"

CAND_DIR="${RUN_ROOT}/candidates"
mkdir -p "${CAND_DIR}"

if [[ ! -d "${SCHEMES_DIR}" ]]; then
  echo "Error: scheme dir not found: ${SCHEMES_DIR}" >&2
  exit 1
fi

echo "[INFO] Materializing FP8 candidates to ${CAND_DIR}"
echo "[INFO] K set: ${KS}"

for k in ${KS}; do
  nodes_file="${SCHEMES_DIR}/nodes_to_exclude_k${k}.txt"
  out_path="${CAND_DIR}/yolov10m-fp8-k${k}.onnx"
  log_dir="${CAND_DIR}/logs/fp8_k${k}"

  echo "[INFO] k=${k} -> ${out_path}"

  RUN_ROOT="${RUN_ROOT}" \
  ONNX_PATH="${ONNX_PATH}" \
  CALIB_PATH="${CALIB_PATH}" \
  OUTPUT_PATH="${out_path}" \
  LOG_DIR="${log_dir}" \
  NODES_TO_EXCLUDE_FILE="${nodes_file}" \
  bash "${REPO_ROOT}/scripts/cv-models/quantize_yolov10m_fp8_onnx.sh"
done

echo "[INFO] Done. Candidates:"
ls -1 "${CAND_DIR}"/*.onnx
